<<-DOC
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
DOC

# @param {String} s
# @param {String} t
# @return {Character}
def find_the_difference(s, t)
    arrOfS = s.split("")
    arrOfT = t.split("")

    missingChar = ""

    arrOfT.each_with_index{ |char, index|
        indexInS = arrOfS.index(char)
        if (indexInS != nil)
            arrOfS.slice!(indexInS)
        else
            missingChar = char
        end
    }

    return missingChar
end
